import type { NextPage } from "next";
import Head from "next/head";
import Hero from "../components/Hero";
import Natural from "../components/Natural";
import Topic from "../components/Topic";
import CoralSouthProject from "../home/CoralSouthProject";
import News from "../home/News";
import PressReleases from "../home/PressReleases";
import Technological from "../home/Technological";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.home}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <PressReleases />
        <Topic />
        <CoralSouthProject />
        <News />
        <Natural />
        <Technological />
      </main>
    </div>
  );
};

export default Home;
