import type { NextPage } from "next";
import Head from "next/head";
import BackgroundImage from "../components/BackgroundImage";
import styles from "../styles/Home.module.scss";
import Explore from "../public/assets/home/images/CoralSouth-project.jpg";
const Home: NextPage = () => {
  return (
    <div className={styles.home}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BackgroundImage image={Explore}>
          <h1>Eni's Coral South project</h1>
          <h5>Towards new horizons with Coral Sul FLNG.</h5>
        </BackgroundImage>
      </main>
    </div>
  );
};

export default Home;
